name: UnitTesting

on: [push]

jobs:
  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.5"
          - "8.4"
          - "8.3"

    steps:
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install dependencies"
        run: composer install --no-progress

      - name: "Check Code Style"
        run: composer phpcs-dry
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: "Run PHP Static Analysis Tool"
        run: vendor/bin/phpstan

      - name: "Run test suite"
        run: vendor/bin/phpunit
